/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsultorIndexRouteImport } from './routes/consultor.index'
import { Route as MovimentacoesTrocaChequesRouteImport } from './routes/movimentacoes.troca-cheques'
import { Route as MovimentacoesTransferenciasRouteImport } from './routes/movimentacoes.transferencias'
import { Route as MovimentacoesTransferenciaRotasRouteImport } from './routes/movimentacoes.transferencia-rotas'
import { Route as MovimentacoesReceitasRouteImport } from './routes/movimentacoes.receitas'
import { Route as MovimentacoesLogAtividadesRouteImport } from './routes/movimentacoes.log-atividades'
import { Route as MovimentacoesHistoricoAppsRouteImport } from './routes/movimentacoes.historico-apps'
import { Route as MovimentacoesEmprestimosVencidosRouteImport } from './routes/movimentacoes.emprestimos-vencidos'
import { Route as MovimentacoesDespesasRouteImport } from './routes/movimentacoes.despesas'
import { Route as MovimentacoesAportesRetiradasRouteImport } from './routes/movimentacoes.aportes-retiradas'
import { Route as FinanceiroFluxoCaixaRouteImport } from './routes/financeiro.fluxo-caixa'
import { Route as FinanceiroContasReceberRouteImport } from './routes/financeiro.contas-receber'
import { Route as FinanceiroContasPagarRouteImport } from './routes/financeiro.contas-pagar'
import { Route as FinanceiroConciliacaoRouteImport } from './routes/financeiro.conciliacao'
import { Route as ConsultorNovoEmprestimoRouteImport } from './routes/consultor.novo-emprestimo'
import { Route as ConsultorDesfazerRouteImport } from './routes/consultor.desfazer'
import { Route as CobrancaTransferirRouteImport } from './routes/cobranca.transferir'
import { Route as CobrancaRenegociacoesRouteImport } from './routes/cobranca.renegociacoes'
import { Route as CobrancaNovoEmprestimoRouteImport } from './routes/cobranca.novo-emprestimo'
import { Route as CobrancaEmprestimosRouteImport } from './routes/cobranca.emprestimos'
import { Route as CobrancaCobrancasDiaRouteImport } from './routes/cobranca.cobrancas-dia'
import { Route as CadastrosUsuariosRouteImport } from './routes/cadastros.usuarios'
import { Route as CadastrosTipoEstabelecimentoRouteImport } from './routes/cadastros.tipo-estabelecimento'
import { Route as CadastrosRotasRouteImport } from './routes/cadastros.rotas'
import { Route as CadastrosFornecedoresRouteImport } from './routes/cadastros.fornecedores'
import { Route as CadastrosFormasRecebimentoRouteImport } from './routes/cadastros.formas-recebimento'
import { Route as CadastrosFeriadosRouteImport } from './routes/cadastros.feriados'
import { Route as CadastrosCredorPromissoriaRouteImport } from './routes/cadastros.credor-promissoria'
import { Route as CadastrosContasBancariasRouteImport } from './routes/cadastros.contas-bancarias'
import { Route as CadastrosConsultoresRouteImport } from './routes/cadastros.consultores'
import { Route as CadastrosClientesRouteImport } from './routes/cadastros.clientes'
import { Route as CadastrosCentrosCustoRouteImport } from './routes/cadastros.centros-custo'
import { Route as CadastrosCategoriasRouteImport } from './routes/cadastros.categorias'
import { Route as AnaliseRotasRouteImport } from './routes/analise.rotas'
import { Route as AnaliseEmprestimosRouteImport } from './routes/analise.emprestimos'
import { Route as AnaliseConsultoresRouteImport } from './routes/analise.consultores'
import { Route as ConsultorEditarNumeroRouteImport } from './routes/consultor.editar.$numero'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorIndexRoute = ConsultorIndexRouteImport.update({
  id: '/consultor/',
  path: '/consultor/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesTrocaChequesRoute =
  MovimentacoesTrocaChequesRouteImport.update({
    id: '/movimentacoes/troca-cheques',
    path: '/movimentacoes/troca-cheques',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovimentacoesTransferenciasRoute =
  MovimentacoesTransferenciasRouteImport.update({
    id: '/movimentacoes/transferencias',
    path: '/movimentacoes/transferencias',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovimentacoesTransferenciaRotasRoute =
  MovimentacoesTransferenciaRotasRouteImport.update({
    id: '/movimentacoes/transferencia-rotas',
    path: '/movimentacoes/transferencia-rotas',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovimentacoesReceitasRoute = MovimentacoesReceitasRouteImport.update({
  id: '/movimentacoes/receitas',
  path: '/movimentacoes/receitas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesLogAtividadesRoute =
  MovimentacoesLogAtividadesRouteImport.update({
    id: '/movimentacoes/log-atividades',
    path: '/movimentacoes/log-atividades',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovimentacoesHistoricoAppsRoute =
  MovimentacoesHistoricoAppsRouteImport.update({
    id: '/movimentacoes/historico-apps',
    path: '/movimentacoes/historico-apps',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovimentacoesEmprestimosVencidosRoute =
  MovimentacoesEmprestimosVencidosRouteImport.update({
    id: '/movimentacoes/emprestimos-vencidos',
    path: '/movimentacoes/emprestimos-vencidos',
    getParentRoute: () => rootRouteImport,
  } as any)
const MovimentacoesDespesasRoute = MovimentacoesDespesasRouteImport.update({
  id: '/movimentacoes/despesas',
  path: '/movimentacoes/despesas',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentacoesAportesRetiradasRoute =
  MovimentacoesAportesRetiradasRouteImport.update({
    id: '/movimentacoes/aportes-retiradas',
    path: '/movimentacoes/aportes-retiradas',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceiroFluxoCaixaRoute = FinanceiroFluxoCaixaRouteImport.update({
  id: '/financeiro/fluxo-caixa',
  path: '/financeiro/fluxo-caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroContasReceberRoute = FinanceiroContasReceberRouteImport.update({
  id: '/financeiro/contas-receber',
  path: '/financeiro/contas-receber',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroContasPagarRoute = FinanceiroContasPagarRouteImport.update({
  id: '/financeiro/contas-pagar',
  path: '/financeiro/contas-pagar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroConciliacaoRoute = FinanceiroConciliacaoRouteImport.update({
  id: '/financeiro/conciliacao',
  path: '/financeiro/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorNovoEmprestimoRoute = ConsultorNovoEmprestimoRouteImport.update({
  id: '/consultor/novo-emprestimo',
  path: '/consultor/novo-emprestimo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorDesfazerRoute = ConsultorDesfazerRouteImport.update({
  id: '/consultor/desfazer',
  path: '/consultor/desfazer',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaTransferirRoute = CobrancaTransferirRouteImport.update({
  id: '/cobranca/transferir',
  path: '/cobranca/transferir',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaRenegociacoesRoute = CobrancaRenegociacoesRouteImport.update({
  id: '/cobranca/renegociacoes',
  path: '/cobranca/renegociacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaNovoEmprestimoRoute = CobrancaNovoEmprestimoRouteImport.update({
  id: '/cobranca/novo-emprestimo',
  path: '/cobranca/novo-emprestimo',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaEmprestimosRoute = CobrancaEmprestimosRouteImport.update({
  id: '/cobranca/emprestimos',
  path: '/cobranca/emprestimos',
  getParentRoute: () => rootRouteImport,
} as any)
const CobrancaCobrancasDiaRoute = CobrancaCobrancasDiaRouteImport.update({
  id: '/cobranca/cobrancas-dia',
  path: '/cobranca/cobrancas-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosUsuariosRoute = CadastrosUsuariosRouteImport.update({
  id: '/cadastros/usuarios',
  path: '/cadastros/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosTipoEstabelecimentoRoute =
  CadastrosTipoEstabelecimentoRouteImport.update({
    id: '/cadastros/tipo-estabelecimento',
    path: '/cadastros/tipo-estabelecimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastrosRotasRoute = CadastrosRotasRouteImport.update({
  id: '/cadastros/rotas',
  path: '/cadastros/rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosFornecedoresRoute = CadastrosFornecedoresRouteImport.update({
  id: '/cadastros/fornecedores',
  path: '/cadastros/fornecedores',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosFormasRecebimentoRoute =
  CadastrosFormasRecebimentoRouteImport.update({
    id: '/cadastros/formas-recebimento',
    path: '/cadastros/formas-recebimento',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastrosFeriadosRoute = CadastrosFeriadosRouteImport.update({
  id: '/cadastros/feriados',
  path: '/cadastros/feriados',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosCredorPromissoriaRoute =
  CadastrosCredorPromissoriaRouteImport.update({
    id: '/cadastros/credor-promissoria',
    path: '/cadastros/credor-promissoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastrosContasBancariasRoute =
  CadastrosContasBancariasRouteImport.update({
    id: '/cadastros/contas-bancarias',
    path: '/cadastros/contas-bancarias',
    getParentRoute: () => rootRouteImport,
  } as any)
const CadastrosConsultoresRoute = CadastrosConsultoresRouteImport.update({
  id: '/cadastros/consultores',
  path: '/cadastros/consultores',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosClientesRoute = CadastrosClientesRouteImport.update({
  id: '/cadastros/clientes',
  path: '/cadastros/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosCentrosCustoRoute = CadastrosCentrosCustoRouteImport.update({
  id: '/cadastros/centros-custo',
  path: '/cadastros/centros-custo',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrosCategoriasRoute = CadastrosCategoriasRouteImport.update({
  id: '/cadastros/categorias',
  path: '/cadastros/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseRotasRoute = AnaliseRotasRouteImport.update({
  id: '/analise/rotas',
  path: '/analise/rotas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseEmprestimosRoute = AnaliseEmprestimosRouteImport.update({
  id: '/analise/emprestimos',
  path: '/analise/emprestimos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnaliseConsultoresRoute = AnaliseConsultoresRouteImport.update({
  id: '/analise/consultores',
  path: '/analise/consultores',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultorEditarNumeroRoute = ConsultorEditarNumeroRouteImport.update({
  id: '/consultor/editar/$numero',
  path: '/consultor/editar/$numero',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analise/consultores': typeof AnaliseConsultoresRoute
  '/analise/emprestimos': typeof AnaliseEmprestimosRoute
  '/analise/rotas': typeof AnaliseRotasRoute
  '/cadastros/categorias': typeof CadastrosCategoriasRoute
  '/cadastros/centros-custo': typeof CadastrosCentrosCustoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/consultores': typeof CadastrosConsultoresRoute
  '/cadastros/contas-bancarias': typeof CadastrosContasBancariasRoute
  '/cadastros/credor-promissoria': typeof CadastrosCredorPromissoriaRoute
  '/cadastros/feriados': typeof CadastrosFeriadosRoute
  '/cadastros/formas-recebimento': typeof CadastrosFormasRecebimentoRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresRoute
  '/cadastros/rotas': typeof CadastrosRotasRoute
  '/cadastros/tipo-estabelecimento': typeof CadastrosTipoEstabelecimentoRoute
  '/cadastros/usuarios': typeof CadastrosUsuariosRoute
  '/cobranca/cobrancas-dia': typeof CobrancaCobrancasDiaRoute
  '/cobranca/emprestimos': typeof CobrancaEmprestimosRoute
  '/cobranca/novo-emprestimo': typeof CobrancaNovoEmprestimoRoute
  '/cobranca/renegociacoes': typeof CobrancaRenegociacoesRoute
  '/cobranca/transferir': typeof CobrancaTransferirRoute
  '/consultor/desfazer': typeof ConsultorDesfazerRoute
  '/consultor/novo-emprestimo': typeof ConsultorNovoEmprestimoRoute
  '/financeiro/conciliacao': typeof FinanceiroConciliacaoRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/movimentacoes/aportes-retiradas': typeof MovimentacoesAportesRetiradasRoute
  '/movimentacoes/despesas': typeof MovimentacoesDespesasRoute
  '/movimentacoes/emprestimos-vencidos': typeof MovimentacoesEmprestimosVencidosRoute
  '/movimentacoes/historico-apps': typeof MovimentacoesHistoricoAppsRoute
  '/movimentacoes/log-atividades': typeof MovimentacoesLogAtividadesRoute
  '/movimentacoes/receitas': typeof MovimentacoesReceitasRoute
  '/movimentacoes/transferencia-rotas': typeof MovimentacoesTransferenciaRotasRoute
  '/movimentacoes/transferencias': typeof MovimentacoesTransferenciasRoute
  '/movimentacoes/troca-cheques': typeof MovimentacoesTrocaChequesRoute
  '/consultor/': typeof ConsultorIndexRoute
  '/consultor/editar/$numero': typeof ConsultorEditarNumeroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analise/consultores': typeof AnaliseConsultoresRoute
  '/analise/emprestimos': typeof AnaliseEmprestimosRoute
  '/analise/rotas': typeof AnaliseRotasRoute
  '/cadastros/categorias': typeof CadastrosCategoriasRoute
  '/cadastros/centros-custo': typeof CadastrosCentrosCustoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/consultores': typeof CadastrosConsultoresRoute
  '/cadastros/contas-bancarias': typeof CadastrosContasBancariasRoute
  '/cadastros/credor-promissoria': typeof CadastrosCredorPromissoriaRoute
  '/cadastros/feriados': typeof CadastrosFeriadosRoute
  '/cadastros/formas-recebimento': typeof CadastrosFormasRecebimentoRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresRoute
  '/cadastros/rotas': typeof CadastrosRotasRoute
  '/cadastros/tipo-estabelecimento': typeof CadastrosTipoEstabelecimentoRoute
  '/cadastros/usuarios': typeof CadastrosUsuariosRoute
  '/cobranca/cobrancas-dia': typeof CobrancaCobrancasDiaRoute
  '/cobranca/emprestimos': typeof CobrancaEmprestimosRoute
  '/cobranca/novo-emprestimo': typeof CobrancaNovoEmprestimoRoute
  '/cobranca/renegociacoes': typeof CobrancaRenegociacoesRoute
  '/cobranca/transferir': typeof CobrancaTransferirRoute
  '/consultor/desfazer': typeof ConsultorDesfazerRoute
  '/consultor/novo-emprestimo': typeof ConsultorNovoEmprestimoRoute
  '/financeiro/conciliacao': typeof FinanceiroConciliacaoRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/movimentacoes/aportes-retiradas': typeof MovimentacoesAportesRetiradasRoute
  '/movimentacoes/despesas': typeof MovimentacoesDespesasRoute
  '/movimentacoes/emprestimos-vencidos': typeof MovimentacoesEmprestimosVencidosRoute
  '/movimentacoes/historico-apps': typeof MovimentacoesHistoricoAppsRoute
  '/movimentacoes/log-atividades': typeof MovimentacoesLogAtividadesRoute
  '/movimentacoes/receitas': typeof MovimentacoesReceitasRoute
  '/movimentacoes/transferencia-rotas': typeof MovimentacoesTransferenciaRotasRoute
  '/movimentacoes/transferencias': typeof MovimentacoesTransferenciasRoute
  '/movimentacoes/troca-cheques': typeof MovimentacoesTrocaChequesRoute
  '/consultor': typeof ConsultorIndexRoute
  '/consultor/editar/$numero': typeof ConsultorEditarNumeroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analise/consultores': typeof AnaliseConsultoresRoute
  '/analise/emprestimos': typeof AnaliseEmprestimosRoute
  '/analise/rotas': typeof AnaliseRotasRoute
  '/cadastros/categorias': typeof CadastrosCategoriasRoute
  '/cadastros/centros-custo': typeof CadastrosCentrosCustoRoute
  '/cadastros/clientes': typeof CadastrosClientesRoute
  '/cadastros/consultores': typeof CadastrosConsultoresRoute
  '/cadastros/contas-bancarias': typeof CadastrosContasBancariasRoute
  '/cadastros/credor-promissoria': typeof CadastrosCredorPromissoriaRoute
  '/cadastros/feriados': typeof CadastrosFeriadosRoute
  '/cadastros/formas-recebimento': typeof CadastrosFormasRecebimentoRoute
  '/cadastros/fornecedores': typeof CadastrosFornecedoresRoute
  '/cadastros/rotas': typeof CadastrosRotasRoute
  '/cadastros/tipo-estabelecimento': typeof CadastrosTipoEstabelecimentoRoute
  '/cadastros/usuarios': typeof CadastrosUsuariosRoute
  '/cobranca/cobrancas-dia': typeof CobrancaCobrancasDiaRoute
  '/cobranca/emprestimos': typeof CobrancaEmprestimosRoute
  '/cobranca/novo-emprestimo': typeof CobrancaNovoEmprestimoRoute
  '/cobranca/renegociacoes': typeof CobrancaRenegociacoesRoute
  '/cobranca/transferir': typeof CobrancaTransferirRoute
  '/consultor/desfazer': typeof ConsultorDesfazerRoute
  '/consultor/novo-emprestimo': typeof ConsultorNovoEmprestimoRoute
  '/financeiro/conciliacao': typeof FinanceiroConciliacaoRoute
  '/financeiro/contas-pagar': typeof FinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof FinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof FinanceiroFluxoCaixaRoute
  '/movimentacoes/aportes-retiradas': typeof MovimentacoesAportesRetiradasRoute
  '/movimentacoes/despesas': typeof MovimentacoesDespesasRoute
  '/movimentacoes/emprestimos-vencidos': typeof MovimentacoesEmprestimosVencidosRoute
  '/movimentacoes/historico-apps': typeof MovimentacoesHistoricoAppsRoute
  '/movimentacoes/log-atividades': typeof MovimentacoesLogAtividadesRoute
  '/movimentacoes/receitas': typeof MovimentacoesReceitasRoute
  '/movimentacoes/transferencia-rotas': typeof MovimentacoesTransferenciaRotasRoute
  '/movimentacoes/transferencias': typeof MovimentacoesTransferenciasRoute
  '/movimentacoes/troca-cheques': typeof MovimentacoesTrocaChequesRoute
  '/consultor/': typeof ConsultorIndexRoute
  '/consultor/editar/$numero': typeof ConsultorEditarNumeroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analise/consultores'
    | '/analise/emprestimos'
    | '/analise/rotas'
    | '/cadastros/categorias'
    | '/cadastros/centros-custo'
    | '/cadastros/clientes'
    | '/cadastros/consultores'
    | '/cadastros/contas-bancarias'
    | '/cadastros/credor-promissoria'
    | '/cadastros/feriados'
    | '/cadastros/formas-recebimento'
    | '/cadastros/fornecedores'
    | '/cadastros/rotas'
    | '/cadastros/tipo-estabelecimento'
    | '/cadastros/usuarios'
    | '/cobranca/cobrancas-dia'
    | '/cobranca/emprestimos'
    | '/cobranca/novo-emprestimo'
    | '/cobranca/renegociacoes'
    | '/cobranca/transferir'
    | '/consultor/desfazer'
    | '/consultor/novo-emprestimo'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/movimentacoes/aportes-retiradas'
    | '/movimentacoes/despesas'
    | '/movimentacoes/emprestimos-vencidos'
    | '/movimentacoes/historico-apps'
    | '/movimentacoes/log-atividades'
    | '/movimentacoes/receitas'
    | '/movimentacoes/transferencia-rotas'
    | '/movimentacoes/transferencias'
    | '/movimentacoes/troca-cheques'
    | '/consultor/'
    | '/consultor/editar/$numero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analise/consultores'
    | '/analise/emprestimos'
    | '/analise/rotas'
    | '/cadastros/categorias'
    | '/cadastros/centros-custo'
    | '/cadastros/clientes'
    | '/cadastros/consultores'
    | '/cadastros/contas-bancarias'
    | '/cadastros/credor-promissoria'
    | '/cadastros/feriados'
    | '/cadastros/formas-recebimento'
    | '/cadastros/fornecedores'
    | '/cadastros/rotas'
    | '/cadastros/tipo-estabelecimento'
    | '/cadastros/usuarios'
    | '/cobranca/cobrancas-dia'
    | '/cobranca/emprestimos'
    | '/cobranca/novo-emprestimo'
    | '/cobranca/renegociacoes'
    | '/cobranca/transferir'
    | '/consultor/desfazer'
    | '/consultor/novo-emprestimo'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/movimentacoes/aportes-retiradas'
    | '/movimentacoes/despesas'
    | '/movimentacoes/emprestimos-vencidos'
    | '/movimentacoes/historico-apps'
    | '/movimentacoes/log-atividades'
    | '/movimentacoes/receitas'
    | '/movimentacoes/transferencia-rotas'
    | '/movimentacoes/transferencias'
    | '/movimentacoes/troca-cheques'
    | '/consultor'
    | '/consultor/editar/$numero'
  id:
    | '__root__'
    | '/'
    | '/analise/consultores'
    | '/analise/emprestimos'
    | '/analise/rotas'
    | '/cadastros/categorias'
    | '/cadastros/centros-custo'
    | '/cadastros/clientes'
    | '/cadastros/consultores'
    | '/cadastros/contas-bancarias'
    | '/cadastros/credor-promissoria'
    | '/cadastros/feriados'
    | '/cadastros/formas-recebimento'
    | '/cadastros/fornecedores'
    | '/cadastros/rotas'
    | '/cadastros/tipo-estabelecimento'
    | '/cadastros/usuarios'
    | '/cobranca/cobrancas-dia'
    | '/cobranca/emprestimos'
    | '/cobranca/novo-emprestimo'
    | '/cobranca/renegociacoes'
    | '/cobranca/transferir'
    | '/consultor/desfazer'
    | '/consultor/novo-emprestimo'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/movimentacoes/aportes-retiradas'
    | '/movimentacoes/despesas'
    | '/movimentacoes/emprestimos-vencidos'
    | '/movimentacoes/historico-apps'
    | '/movimentacoes/log-atividades'
    | '/movimentacoes/receitas'
    | '/movimentacoes/transferencia-rotas'
    | '/movimentacoes/transferencias'
    | '/movimentacoes/troca-cheques'
    | '/consultor/'
    | '/consultor/editar/$numero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnaliseConsultoresRoute: typeof AnaliseConsultoresRoute
  AnaliseEmprestimosRoute: typeof AnaliseEmprestimosRoute
  AnaliseRotasRoute: typeof AnaliseRotasRoute
  CadastrosCategoriasRoute: typeof CadastrosCategoriasRoute
  CadastrosCentrosCustoRoute: typeof CadastrosCentrosCustoRoute
  CadastrosClientesRoute: typeof CadastrosClientesRoute
  CadastrosConsultoresRoute: typeof CadastrosConsultoresRoute
  CadastrosContasBancariasRoute: typeof CadastrosContasBancariasRoute
  CadastrosCredorPromissoriaRoute: typeof CadastrosCredorPromissoriaRoute
  CadastrosFeriadosRoute: typeof CadastrosFeriadosRoute
  CadastrosFormasRecebimentoRoute: typeof CadastrosFormasRecebimentoRoute
  CadastrosFornecedoresRoute: typeof CadastrosFornecedoresRoute
  CadastrosRotasRoute: typeof CadastrosRotasRoute
  CadastrosTipoEstabelecimentoRoute: typeof CadastrosTipoEstabelecimentoRoute
  CadastrosUsuariosRoute: typeof CadastrosUsuariosRoute
  CobrancaCobrancasDiaRoute: typeof CobrancaCobrancasDiaRoute
  CobrancaEmprestimosRoute: typeof CobrancaEmprestimosRoute
  CobrancaNovoEmprestimoRoute: typeof CobrancaNovoEmprestimoRoute
  CobrancaRenegociacoesRoute: typeof CobrancaRenegociacoesRoute
  CobrancaTransferirRoute: typeof CobrancaTransferirRoute
  ConsultorDesfazerRoute: typeof ConsultorDesfazerRoute
  ConsultorNovoEmprestimoRoute: typeof ConsultorNovoEmprestimoRoute
  FinanceiroConciliacaoRoute: typeof FinanceiroConciliacaoRoute
  FinanceiroContasPagarRoute: typeof FinanceiroContasPagarRoute
  FinanceiroContasReceberRoute: typeof FinanceiroContasReceberRoute
  FinanceiroFluxoCaixaRoute: typeof FinanceiroFluxoCaixaRoute
  MovimentacoesAportesRetiradasRoute: typeof MovimentacoesAportesRetiradasRoute
  MovimentacoesDespesasRoute: typeof MovimentacoesDespesasRoute
  MovimentacoesEmprestimosVencidosRoute: typeof MovimentacoesEmprestimosVencidosRoute
  MovimentacoesHistoricoAppsRoute: typeof MovimentacoesHistoricoAppsRoute
  MovimentacoesLogAtividadesRoute: typeof MovimentacoesLogAtividadesRoute
  MovimentacoesReceitasRoute: typeof MovimentacoesReceitasRoute
  MovimentacoesTransferenciaRotasRoute: typeof MovimentacoesTransferenciaRotasRoute
  MovimentacoesTransferenciasRoute: typeof MovimentacoesTransferenciasRoute
  MovimentacoesTrocaChequesRoute: typeof MovimentacoesTrocaChequesRoute
  ConsultorIndexRoute: typeof ConsultorIndexRoute
  ConsultorEditarNumeroRoute: typeof ConsultorEditarNumeroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor/': {
      id: '/consultor/'
      path: '/consultor'
      fullPath: '/consultor/'
      preLoaderRoute: typeof ConsultorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/troca-cheques': {
      id: '/movimentacoes/troca-cheques'
      path: '/movimentacoes/troca-cheques'
      fullPath: '/movimentacoes/troca-cheques'
      preLoaderRoute: typeof MovimentacoesTrocaChequesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/transferencias': {
      id: '/movimentacoes/transferencias'
      path: '/movimentacoes/transferencias'
      fullPath: '/movimentacoes/transferencias'
      preLoaderRoute: typeof MovimentacoesTransferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/transferencia-rotas': {
      id: '/movimentacoes/transferencia-rotas'
      path: '/movimentacoes/transferencia-rotas'
      fullPath: '/movimentacoes/transferencia-rotas'
      preLoaderRoute: typeof MovimentacoesTransferenciaRotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/receitas': {
      id: '/movimentacoes/receitas'
      path: '/movimentacoes/receitas'
      fullPath: '/movimentacoes/receitas'
      preLoaderRoute: typeof MovimentacoesReceitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/log-atividades': {
      id: '/movimentacoes/log-atividades'
      path: '/movimentacoes/log-atividades'
      fullPath: '/movimentacoes/log-atividades'
      preLoaderRoute: typeof MovimentacoesLogAtividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/historico-apps': {
      id: '/movimentacoes/historico-apps'
      path: '/movimentacoes/historico-apps'
      fullPath: '/movimentacoes/historico-apps'
      preLoaderRoute: typeof MovimentacoesHistoricoAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/emprestimos-vencidos': {
      id: '/movimentacoes/emprestimos-vencidos'
      path: '/movimentacoes/emprestimos-vencidos'
      fullPath: '/movimentacoes/emprestimos-vencidos'
      preLoaderRoute: typeof MovimentacoesEmprestimosVencidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/despesas': {
      id: '/movimentacoes/despesas'
      path: '/movimentacoes/despesas'
      fullPath: '/movimentacoes/despesas'
      preLoaderRoute: typeof MovimentacoesDespesasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimentacoes/aportes-retiradas': {
      id: '/movimentacoes/aportes-retiradas'
      path: '/movimentacoes/aportes-retiradas'
      fullPath: '/movimentacoes/aportes-retiradas'
      preLoaderRoute: typeof MovimentacoesAportesRetiradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/fluxo-caixa': {
      id: '/financeiro/fluxo-caixa'
      path: '/financeiro/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof FinanceiroFluxoCaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/contas-receber': {
      id: '/financeiro/contas-receber'
      path: '/financeiro/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof FinanceiroContasReceberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/contas-pagar': {
      id: '/financeiro/contas-pagar'
      path: '/financeiro/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof FinanceiroContasPagarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/conciliacao': {
      id: '/financeiro/conciliacao'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof FinanceiroConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor/novo-emprestimo': {
      id: '/consultor/novo-emprestimo'
      path: '/consultor/novo-emprestimo'
      fullPath: '/consultor/novo-emprestimo'
      preLoaderRoute: typeof ConsultorNovoEmprestimoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor/desfazer': {
      id: '/consultor/desfazer'
      path: '/consultor/desfazer'
      fullPath: '/consultor/desfazer'
      preLoaderRoute: typeof ConsultorDesfazerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca/transferir': {
      id: '/cobranca/transferir'
      path: '/cobranca/transferir'
      fullPath: '/cobranca/transferir'
      preLoaderRoute: typeof CobrancaTransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca/renegociacoes': {
      id: '/cobranca/renegociacoes'
      path: '/cobranca/renegociacoes'
      fullPath: '/cobranca/renegociacoes'
      preLoaderRoute: typeof CobrancaRenegociacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca/novo-emprestimo': {
      id: '/cobranca/novo-emprestimo'
      path: '/cobranca/novo-emprestimo'
      fullPath: '/cobranca/novo-emprestimo'
      preLoaderRoute: typeof CobrancaNovoEmprestimoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca/emprestimos': {
      id: '/cobranca/emprestimos'
      path: '/cobranca/emprestimos'
      fullPath: '/cobranca/emprestimos'
      preLoaderRoute: typeof CobrancaEmprestimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cobranca/cobrancas-dia': {
      id: '/cobranca/cobrancas-dia'
      path: '/cobranca/cobrancas-dia'
      fullPath: '/cobranca/cobrancas-dia'
      preLoaderRoute: typeof CobrancaCobrancasDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/usuarios': {
      id: '/cadastros/usuarios'
      path: '/cadastros/usuarios'
      fullPath: '/cadastros/usuarios'
      preLoaderRoute: typeof CadastrosUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/tipo-estabelecimento': {
      id: '/cadastros/tipo-estabelecimento'
      path: '/cadastros/tipo-estabelecimento'
      fullPath: '/cadastros/tipo-estabelecimento'
      preLoaderRoute: typeof CadastrosTipoEstabelecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/rotas': {
      id: '/cadastros/rotas'
      path: '/cadastros/rotas'
      fullPath: '/cadastros/rotas'
      preLoaderRoute: typeof CadastrosRotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/fornecedores': {
      id: '/cadastros/fornecedores'
      path: '/cadastros/fornecedores'
      fullPath: '/cadastros/fornecedores'
      preLoaderRoute: typeof CadastrosFornecedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/formas-recebimento': {
      id: '/cadastros/formas-recebimento'
      path: '/cadastros/formas-recebimento'
      fullPath: '/cadastros/formas-recebimento'
      preLoaderRoute: typeof CadastrosFormasRecebimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/feriados': {
      id: '/cadastros/feriados'
      path: '/cadastros/feriados'
      fullPath: '/cadastros/feriados'
      preLoaderRoute: typeof CadastrosFeriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/credor-promissoria': {
      id: '/cadastros/credor-promissoria'
      path: '/cadastros/credor-promissoria'
      fullPath: '/cadastros/credor-promissoria'
      preLoaderRoute: typeof CadastrosCredorPromissoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/contas-bancarias': {
      id: '/cadastros/contas-bancarias'
      path: '/cadastros/contas-bancarias'
      fullPath: '/cadastros/contas-bancarias'
      preLoaderRoute: typeof CadastrosContasBancariasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/consultores': {
      id: '/cadastros/consultores'
      path: '/cadastros/consultores'
      fullPath: '/cadastros/consultores'
      preLoaderRoute: typeof CadastrosConsultoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/clientes': {
      id: '/cadastros/clientes'
      path: '/cadastros/clientes'
      fullPath: '/cadastros/clientes'
      preLoaderRoute: typeof CadastrosClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/centros-custo': {
      id: '/cadastros/centros-custo'
      path: '/cadastros/centros-custo'
      fullPath: '/cadastros/centros-custo'
      preLoaderRoute: typeof CadastrosCentrosCustoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastros/categorias': {
      id: '/cadastros/categorias'
      path: '/cadastros/categorias'
      fullPath: '/cadastros/categorias'
      preLoaderRoute: typeof CadastrosCategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise/rotas': {
      id: '/analise/rotas'
      path: '/analise/rotas'
      fullPath: '/analise/rotas'
      preLoaderRoute: typeof AnaliseRotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise/emprestimos': {
      id: '/analise/emprestimos'
      path: '/analise/emprestimos'
      fullPath: '/analise/emprestimos'
      preLoaderRoute: typeof AnaliseEmprestimosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analise/consultores': {
      id: '/analise/consultores'
      path: '/analise/consultores'
      fullPath: '/analise/consultores'
      preLoaderRoute: typeof AnaliseConsultoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultor/editar/$numero': {
      id: '/consultor/editar/$numero'
      path: '/consultor/editar/$numero'
      fullPath: '/consultor/editar/$numero'
      preLoaderRoute: typeof ConsultorEditarNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnaliseConsultoresRoute: AnaliseConsultoresRoute,
  AnaliseEmprestimosRoute: AnaliseEmprestimosRoute,
  AnaliseRotasRoute: AnaliseRotasRoute,
  CadastrosCategoriasRoute: CadastrosCategoriasRoute,
  CadastrosCentrosCustoRoute: CadastrosCentrosCustoRoute,
  CadastrosClientesRoute: CadastrosClientesRoute,
  CadastrosConsultoresRoute: CadastrosConsultoresRoute,
  CadastrosContasBancariasRoute: CadastrosContasBancariasRoute,
  CadastrosCredorPromissoriaRoute: CadastrosCredorPromissoriaRoute,
  CadastrosFeriadosRoute: CadastrosFeriadosRoute,
  CadastrosFormasRecebimentoRoute: CadastrosFormasRecebimentoRoute,
  CadastrosFornecedoresRoute: CadastrosFornecedoresRoute,
  CadastrosRotasRoute: CadastrosRotasRoute,
  CadastrosTipoEstabelecimentoRoute: CadastrosTipoEstabelecimentoRoute,
  CadastrosUsuariosRoute: CadastrosUsuariosRoute,
  CobrancaCobrancasDiaRoute: CobrancaCobrancasDiaRoute,
  CobrancaEmprestimosRoute: CobrancaEmprestimosRoute,
  CobrancaNovoEmprestimoRoute: CobrancaNovoEmprestimoRoute,
  CobrancaRenegociacoesRoute: CobrancaRenegociacoesRoute,
  CobrancaTransferirRoute: CobrancaTransferirRoute,
  ConsultorDesfazerRoute: ConsultorDesfazerRoute,
  ConsultorNovoEmprestimoRoute: ConsultorNovoEmprestimoRoute,
  FinanceiroConciliacaoRoute: FinanceiroConciliacaoRoute,
  FinanceiroContasPagarRoute: FinanceiroContasPagarRoute,
  FinanceiroContasReceberRoute: FinanceiroContasReceberRoute,
  FinanceiroFluxoCaixaRoute: FinanceiroFluxoCaixaRoute,
  MovimentacoesAportesRetiradasRoute: MovimentacoesAportesRetiradasRoute,
  MovimentacoesDespesasRoute: MovimentacoesDespesasRoute,
  MovimentacoesEmprestimosVencidosRoute: MovimentacoesEmprestimosVencidosRoute,
  MovimentacoesHistoricoAppsRoute: MovimentacoesHistoricoAppsRoute,
  MovimentacoesLogAtividadesRoute: MovimentacoesLogAtividadesRoute,
  MovimentacoesReceitasRoute: MovimentacoesReceitasRoute,
  MovimentacoesTransferenciaRotasRoute: MovimentacoesTransferenciaRotasRoute,
  MovimentacoesTransferenciasRoute: MovimentacoesTransferenciasRoute,
  MovimentacoesTrocaChequesRoute: MovimentacoesTrocaChequesRoute,
  ConsultorIndexRoute: ConsultorIndexRoute,
  ConsultorEditarNumeroRoute: ConsultorEditarNumeroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
